### ISSUE TITLE
[STEP4] dificuldade ao mover cards no final das pilhas para fazer o rating

### ISSUE THREAD

**Issue by bfsc** [bfsc/qmethod#10]
"estou tentando responder, mas mover os cartões da pilha Agree para a pilha 3, por exemplo, não está funcionando no meu computador... quando as que quero mover estão muito abaixo na pilha Agree. Estou usando o Google Chrome. Alguma dica quanto a isso?"

![2018-08-14b](https://user-images.githubusercontent.com/1893620/44156065-60d36812-a085-11e8-8b69-3938bff464e0.png)

**Comment by pmop** [comment]
On https://github.com/bfsc/qmethod/issues/14
Fixed by https://github.com/bfsc/qmethod/pull/13

**Comment by pmop** [comment]
Fixed by https://github.com/bfsc/qmethod/pull/17
