### ISSUE TITLE
[STEP 3] cards "fantasmas"

### ISSUE THREAD

**Issue by bfsc** [bfsc/qmethod#12]
"estou tendo problemas para responder o survey. quando tento arrastar e soltar, as vezes aparecem esses quadrados cinzas que, acredito, não sejam esperados. em algumas situações, não consigo "soltar" o quadro para nenhum dos paineis coloridos"

SO: Linux
Browser: Firefox

![whatsapp image 2018-08-15 at 12 00 17 1](https://user-images.githubusercontent.com/1893620/44156479-540d8080-a086-11e8-881d-4f266a1b3b82.jpeg)
![whatsapp image 2018-08-15 at 12 00 17](https://user-images.githubusercontent.com/1893620/44156481-54369d58-a086-11e8-9bc8-c45fb0bf42f3.jpeg)

**Comment by pmop** [comment]
Fixed by latest changes, maybe?
