### ISSUE TITLE
caracteres estranhos em alguns cards

### ISSUE THREAD

**Issue by bfsc** [bfsc/qmethod#15]
alem do card mostrado na figura abaxo, há outros cards com caracteres estranho tambe. entao é importante dar uma olhada geral em todos os cards.

![image](https://user-images.githubusercontent.com/1893620/44161926-16ecf780-a095-11e8-881a-59d942abd577.png)

**Comment by pmop** [comment]
Não é um bug. Está seguindo o comportamento esperado. O texto está exatamente desse jeito em settings/statements.xml.

**Comment by bfsc** [comment]
entao houve algum problema de codificação na hora de copiar do javascript pra o xml, pq quando as statement estava hard-coded no codigo javascript essas barras nao existiam.

**Comment by pmop** [comment]
Só remover editando o próprio xml que está em settings. O github permite fazer isso aqui mesmo.

**Comment by pmop** [comment]
Fixed by: https://github.com/bfsc/qmethod/pull/19
