### ISSUE TITLE
[STEP3] botões de help e back posicionado errados

### ISSUE THREAD

**Issue by bfsc** [bfsc/qmethod#18]
atualmente está como na figura abaixo, a esquerda da tela e sobrepondo parte do scroll de disagree:

![image](https://user-images.githubusercontent.com/1893620/44226511-bc23d080-a166-11e8-9e2c-0f33553ad9f6.png)

deveria seguir o padrão e manter esses botões centralizados na tela, e sem se sobrepor aos scrolls. deve ser como na tela do step 4.

**Comment by pmop** [comment]
Mudei justamente para não colidir. Não é possível deixar centralizado pois falta espaço vertical no browser (como é possível notar na figura). Uma solução é remover um pouco de espaço vertical das listas.

**Comment by bfsc** [comment]
como assim falta espaço vertical? não seria o caso de botar os botões mais pra baixo usando tags `<br/>` ou algo similar?

**Comment by pmop** [comment]
No html, ele já está com bottom:0

**Comment by bfsc** [comment]
tem q dar uma olhada pra ver como consegue consertar isso pq no safari, por exemplo, isso fica ainda mais critico. olha so esse print que gustavo tirou usando no safari

![image](https://user-images.githubusercontent.com/1893620/44227417-eb3b4180-a168-11e8-8c28-6157416cd844.png)
