### ISSUE TITLE
[STEP4] os ratings estão invertidos

### ISSUE THREAD

**Issue by bfsc** [bfsc/qmethod#20]
no step 4, os ratings positivos (+3, +2 e +1) estão do lado aposto a coluna de agree, assim como os ratings negativos (-3, -2 e -1) estão do lado aposto da coluna de disagree... is prejudica a usabilidade, já que entende-se que os cards q estao na coluna de agree serao naturalmente arrastados para os ratings positivos e vice-versa

![image](https://user-images.githubusercontent.com/1893620/44228018-897bd700-a16a-11e8-9157-1c4bef484b95.png)

**Comment by pmop** [comment]
Fixed by: https://github.com/bfsc/qmethod/pull/21
